[package]
name = "day02"
version = "0.1.0"
edition = "2024"

[dependencies]
log = {version = "0.4", features = ["max_level_debug", "release_max_level_info"]}
env_logger = "0.11.8"
regex = "1.10"
anyhow = "1.0.100"