[package]
name = "day05"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4", features = ["derive"]}
env_logger = "0.11.8"
log = {version = "0.4", features = ["max_level_debug", "release_max_level_info"]}
regex = "1.10"